language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
    - composer self-update

install:
    - composer --prefer-source install

notifications:
  email:
    - payumsupport@forma-pro.com
